name: Build Images

on:
    # Trigger the action manually from the UI
    workflow_dispatch:
      inputs:
        target:
          description: 'Image to build'
          required: true
          default: 'targets'
          type: choice
          options:
            - 'jupyter'
            - 'frontend'
            - 'api'
            - 'streamlit_app'

    # Trigger the action when I create or push a `release/**` branch
    push:
      branches:
        - 'master'

env:
    DOCKER_REGISTRY_URL: docker.io
    DOCKER_REPO_NAME: jibutech

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            token: ${{ secrets.GH_PAT }}
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker registry
          uses: docker/login-action@v2
          with:
            registry: docker.io
            username: ${{ secrets.REGISTRY_USER }}
            password: ${{ secrets.REGISTRY_PASS }}
        - name: Build and push Docker images
          run: |
            path=`pwd`

            if [[ "${TARGET}" == "jupyter" ]];then
              cd ${path}/jupyter; docker buildx build  --platform linux/amd64 --tag ${DOCKER_REGISTRY_URL}/${DOCKER_REPO_NAME}/generative-ai-jupyter:latest --push .
            fi

            if [[ "${TARGET}" == "frontend" ]];then
              cd ${path}/frontend; docker buildx build  --platform linux/amd64 --tag ${DOCKER_REGISTRY_URL}/${DOCKER_REPO_NAME}/generative-ai-frontend:latest --push .
            fi

            if [[ "${TARGET}" == "api" ]];then
              cd ${path}/api; docker buildx build  --platform linux/amd64 --tag ${DOCKER_REGISTRY_URL}/${DOCKER_REPO_NAME}/generative-ai-api:latest --push .
            fi

            if [[ "${TARGET}" == "streamlit_app" ]];then
              cd ${path}/streamlit_app; docker buildx build  --platform linux/amd64 --tag ${DOCKER_REGISTRY_URL}/${DOCKER_REPO_NAME}/generative-ai-streamlit-app:latest --push .
            fi

          env:
            TARGET: ${{ inputs.target }}